# Generated by Django 2.2 on 2021-10-22 05:11

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211022_0510'),
        # ('accounts', '0006_auto_20211021_1700'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
    ]
