# Generated by Django 2.2 on 2021-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211019_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedat',
            new_name='updated_at',
        ),
    ]
