# Generated by Django 2.2 on 2021-10-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211021_1700'),
        ('accounts', '0006_auto_20211022_0511'),
    ]

    operations = [
    ]
