# Generated by Django 2.2 on 2021-10-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurantname',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurantname',
            new_name='restaurant',
        ),
    ]
