# Generated by Django 2.2 on 2021-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20211018_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Dispatched'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Placed')], default=5),
        ),
    ]
