# Generated by Django 2.2 on 2021-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20211019_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
