# Generated by Django 2.2 on 2021-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20211020_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='updatedat',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updatedat',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderfood',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderfood',
            old_name='updatedat',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='updatedat',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
