# Generated by Django 2.2 on 2021-10-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20211022_0510'),
        ('restaurant', '0010_auto_20211021_1700'),
    ]

    operations = [
    ]
